(toggle-debug-on-error)
(require 'elmpd)
(setq conn (elmpd-connect :name "test-connection"))
(defun test-cb (conn err text)
  (message "test-cb: %s|%s|%s" conn err text))
(defun test-cb2 (conn subsys)
  (message "test-cb2: %s|%s" conn subsys))
 (elmpd-send conn "status" 'test-cb)
;; (elmpd-send conn "albumart \"Q-R/Roxy Music - Avalon (1999 Digital Remaster).mp3\" 0" 'test-cb)

(setq conn2 (elmpd-connect :name "test-idle-connection" :subsystems '(all . test-cb2)))
(elmpd-send conn2 "ping" 'test-cb)
(elmpd-send conn "play" 'test-cb)
(elmpd-send conn "stop" 'test-cb)
